/**
 * Token registry (Foundry-style single entry point).
 *
 * Gumroad Foundry ships tokens as JS objects that are compiled into a
 * theme CSS file; here `styles/tokens.css` is the compiled artifact of
 * these objects. Keep both in sync (the CSS file is generated by hand
 * from this module — variable names mirror the keys 1:1).
 */
import { semantic, palette } from './colors.js';
import { spacing } from './spacing.js';
import { typography } from './typography.js';
import { radii } from './radii.js';
import { shadows } from './shadows.js';
import { motion } from './motion.js';
import { zindex } from './zindex.js';

export { semantic, palette, spacing, typography, radii, shadows, motion, zindex };

/** Flat { 'nb-...': value } map, handy for tests / tooling. */
export function toCssVarMap(theme = 'light') {
    const vars = {};
    const s = semantic[theme] || semantic.light;
    for (const [k, v] of Object.entries(s)) vars[`--nb-${k}`] = v;
    for (const [k, v] of Object.entries(spacing)) vars[`--nb-space-${k}`] = `${v}px`;
    for (const [k, v] of Object.entries(typography.font)) vars[`--nb-font-${k}`] = v;
    for (const [k, v] of Object.entries(typography.size)) vars[`--nb-text-${k}`] = v;
    for (const [k, v] of Object.entries(typography.weight)) vars[`--nb-weight-${k}`] = v;
    for (const [k, v] of Object.entries(radii)) vars[`--nb-radius-${k}`] = `${v}px`;
    for (const [k, v] of Object.entries(shadows)) vars[`--nb-shadow-geo-${k}`] = v;
    for (const [k, v] of Object.entries(motion.duration)) vars[`--nb-duration-${k}`] = v;
    for (const [k, v] of Object.entries(motion.easing)) vars[`--nb-easing-${k}`] = v;
    for (const [k, v] of Object.entries(zindex)) vars[`--nb-z-${k}`] = v;
    return vars;
}
